### ISSUE TITLE
Field input.handle is required

### ISSUE THREAD

**Issue by goleary** [pocesar/actor-twitter-scraper#10]
I'm trying to use this through APIFY to obtain tweets from a particular thread, but am a little bit confused about part of the configuration.

The readme mentions:
> List of Handles - Specify a list of Twitter handles (usernames) you want to scrape shall the crawler visit. If zero, the actor ignores the links and only crawls the Start URLs.

But when I try to save the config with no handles specified & a start URL I get an error:

![image](https://user-images.githubusercontent.com/16123225/125537285-777c193a-b92a-4187-be67-40bf27f0d8b4.png)

**Comment by zpelechova** [comment]
Hey, this should be fixed by now, if it still happens like that, please change the version in setting to version-1 and save.
