### ISSUE TITLE
Advanced searches are always limited to 40 results lately?

### ISSUE THREAD

**Issue by BobbyWibowo** [pocesar/actor-twitter-scraper#11]
This appears to be the current behavior live on Twitter as well when I try to do some searches directly, regardless of using Top or Latest/Live tabs. Is there something wrong on my end, or is it just the new policy on Twitter?

**Comment by pocesar** [comment]
the number of tweets vary depending on what you search, you can check the behavior logged in and on incognito, they are inconsistent (by Twitter's will). it seems "top" will return at most 24h selected tweets (don't know the criteria) and latest / live they can only come "new", trying to go to the past tweets is also limited
