### ISSUE TITLE
Parser is broken. I found a fix, though.

### ISSUE THREAD

**Issue by James-Darko** [pocesar/actor-twitter-scraper#17]
Hi,

Twitter seems to have updated the timeline field in the json. Change the first timeline on line 333 in main.js to timeline_v2. 

`data?.data?.user?.result?.timeline_v2?.timeline?.instructions?.length`

The line below needs updating as well. Working on my end with this fix.

**Comment by pocesar** [comment]
hi @James-Darko thanks for the report. I'll fix it and release a new version in a bit

**Comment by pocesar** [comment]
done, it's available here and on [apify.com/](https://apify.com/vdrmota/twitter-scraper)
